name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

   # - name: Compile
     # run: javac -d target GCS/src/**/*.java

    - name: Compile and run tests
      run: javac -cp ".:$GITHUB_WORKSPACE/junit.jar" -d GCS/bin GCS/src/**/*.java && java -cp "GCS/bin:$GITHUB_WORKSPACE/junit.jar" tests.YourTestClassName

