name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

   # - name: Compile
     # run: javac -d target GCS/src/**/*.java

    - name: Compile and run tests
      run: javac -cp ".:$GITHUB_WORKSPACE/GCS/junit-platform-console-standalone-1.8.0-M1.jar" -d target src/**/*.java && java -cp "target:$GITHUB_WORKSPACE/GCS/junit-platform-console-standalone-1.8.0-M1.jar" org.junit.runner.JUnitCore "target:$GITHUB_WORKSPACE/GCS/src/tests/**.java" 
